version: '3.8'

volumes:
 prometheus_data: {}
 grafana_data: {}

services:
  node-red:
    build: node-red
    container_name: node-red
    networks:
      - node_red
    ports:
      - "1880:1880"
    depends_on:
      - grafana
    environment:
      #GIT_BRANCH: ${GIT_BRANCH}
      
      # Miljøvariablen FLOWS fortæller Node-RED IDEet hvilket flow.json den skal åbne og gemme ændringer i ved deploy.
      FLOWS: "/data/flows.json"
      
      # Bind mount fra codespace til den kørende containers /data.
      # Gør det muligt at deploye flowkode direkte fra IDE og bruge git til at comitte ændringerne til repo.
    volumes:
      - ./node-red/:/data

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

    networks:
      - node_red
  
  grafana:
    image: grafana/grafana
    user: '472'
    restart: always
    #environment:
      #GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    ports:
      - 3000:3000
    networks:
      - node_red
    depends_on:
      - prometheus
networks:
  node_red: